# -*- coding: utf-8 -*-
"""TrainTestSplit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GJJ5yBouXp8yiacte_6VJpKg7m9rdFTt
"""

import duckdb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import duckdb

#from google.colab import drive
#drive.mount('/content/drive')

conn_input = duckdb.connect(database='/content/drive/MyDrive/ADSDB/colabs-part2/Data Preparation/prepared_data.db', read_only=True)
conn_out = duckdb.connect('/content/drive/MyDrive/ADSDB/colabs-part2/Train and Validation Sets Generation/prepared_data_splitted.db')

# Print tables in input database
result = conn_input.execute("SHOW TABLES;")

rows = result.fetchall()
for row in rows:
    print(row[0])

df = conn_input.execute("SELECT * FROM prepared_data").df()
df.head()

train_set = df.iloc[4:]
val_set = df.iloc[:4]

# Print the dimensions of each set
print("\nDimensions of Train Set:", train_set.shape)
print("Dimensions of Test Set:", val_set.shape)

# Create tables in the output database

conn_out.execute("""
CREATE OR REPLACE TABLE train AS
SELECT *
FROM train_set;
""")

conn_out.execute("""
CREATE OR REPLACE TABLE val AS
SELECT *
FROM val_set;
""")

# Print tables in conn_out
result = conn_out.execute("SHOW TABLES;")

rows = result.fetchall()
for row in rows:
    print(row[0])

# Close and save databases

conn_input.close()
conn_out.close()