# -*- coding: utf-8 -*-
"""run_all.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AE_G8zCAYC1wmkZINY9K4XLQdi5vpCxz
"""

# Commented out IPython magic to ensure Python compatibility.
# Import necessary libraries and modules
from google.colab import drive
import psutil
import os
import logging


# Mount Google Drive
drive.mount('/content/drive')

# Change to the directory containing your scripts
# %cd /content/drive/My Drive/ADSDB/operations

# Install necessary libraries
!pip install psutil

# Define the monitor_performance function
def monitor_performance():
    """
    Function to print basic system performance metrics.
    """
    print("\n--- System Performance Metrics ---")
    print(f"CPU Usage: {psutil.cpu_percent()}%")
    print(f"Memory Usage: {psutil.virtual_memory().percent}%")
    print("----------------------------------\n")


# Set up logging
logging.basicConfig(filename='script_execution.log', level=logging.INFO,
                    format='%(asctime)s - %(levelname)s - %(message)s')

def execute_script(script_name):
    """
    Execute a given Python script and handle potential errors.
    """
    # Create/overwrite a file for the script's error output
    error_file_path = f"{script_name}_error.log"

    # Run the script and redirect its stderr to the error file
    exit_code = os.system(f"python {script_name} 2>{error_file_path}")

    if exit_code == 0:
        print(f"Execution of {script_name} completed successfully!")
        logging.info(f"Execution of {script_name} completed successfully!")
        # If no errors, remove the error log file for cleanliness
        os.remove(error_file_path)
    else:
        print(f"Error executing {script_name}. Check {error_file_path} for details.")
        with open(error_file_path, 'r') as err_file:
            # Log the contents of the error file
            logging.error(f"Error executing {script_name}. Details:\n{err_file.read()}")
        monitor_performance()

# List of scripts to execute
scripts = [
    "file_separation.py", "formatted_zone.py", "trusted_zone.py", "check_duplicates.py",
    "data_profiling.py", "exploitation_zone.py"
]

# Execute each script in the list
for script in scripts:
    execute_script(script)